name: iris_pipeline

channels:
    - http://ssb.stsci.edu/astroconda-dev
    - defaults

dependencies:
    - python>=3.6
    - astropy
    - Cython
    - matplotlib
    - numpy
    - jwst
    - pip:
      - sphinx-astropy
