name: iris_pipeline

channels:
    - astropy

dependencies:
    - python>=3.6
    - sphinx=1.7
    - astropy
    - pip:
      - sphinx-astropy
      - recommonmark
      - git+https://github.com/zonca/jwst.git@iris_devel
