name: iris_pipeline

channels:
    - astropy

dependencies:
    - python==3.6
    - astropy
    - pip
    - pip:
      - sphinx-astropy
      - https://github.com/spacetelescope/jwst/archive/0.13.7.zip
