name: iris_pipeline

channels:
    - astropy

dependencies:
    - python>=3.6
    - astropy
    - Cython
    - matplotlib
    - numpy
    - pip:
      - sphinx-astropy
      - git+https://github.com/zonca/jwst.git@iris_devel
