name: iris_pipeline

channels:
    - astropy
    - http://ssb.stsci.edu/astroconda-dev

dependencies:
    - python>=3.6
    - astropy
    - Cython
    - matplotlib
    - numpy
    - sphinx-astropy
    - jwst
#   - pip:
#       - dependency_from_pip
