name: iris_pipeline

channels:
    - astropy

dependencies:
    - python>=3.6
    - astropy
    - pip:
      - sphinx-astropy
      - https://github.com/rtfd/recommonmark/archive/fix-math.zip
      - git+https://github.com/zonca/jwst.git@iris_devel
